$(document).ready(function(){
    $('#Ninja1').click(function(){
        $(this).hide();
    })
    $('#Ninja2').click(function(){
        $(this).hide();
    })
    $('#Ninja3').click(function(){
        $(this).hide();
    })
    $('#Ninja4').click(function(){
        $(this).hide();
    })
    $('#Ninja5').click(function(){
        $(this).hide();
    })
    $('#Ninja6').click(function(){
        $(this).hide();
    })
    $('#Ninja7').click(function(){
        $(this).hide();
    })
    $('#Ninja8').click(function(){
        $(this).hide();
    })
    
    $('#Restore').click(function() {
        $('.Ninja').show();
    })
})